spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/sea_battle
    user: postgres
    password: 12345
  datasource:
    url: jdbc:postgresql://localhost:5432/sea_battle
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
