spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/sea_battle
    user: postgres
    password: 12345
  datasource:
    url: jdbc:postgresql://localhost:5432/sea_battle
    username: postgres
    password: 12345
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

jwt:
  issuer: 'starovoytov@gmail.com'
  signingKey: 'talspoc120nxjsapqke1d77'
  aTokenDuration: 30
  rTokenDuration: 168
